name: gps_massageapp
description: A GPS Massage Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_line_sdk: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  search_page: any
  curved_navigation_bar:
  flutter_markdown: ^0.5.1
  pin_code_fields: ^5.2.0
  flutter_rating_bar: ^3.2.0+1
  connectivity: ^2.0.2 # Yogeshwar for checking Internet connection
  shared_preferences: # Yogeshwar storing data locally throughout the app
  provider: any
  toast: # Yogeshwar Toast messages to indicate the progress completion
  getwidget: any # Yogeshwar get widget for Loading indicators
  http: ^0.12.2 # Yogeshwar HTTP Network calls for API's
  uuid: ^2.0.4
  flutter_google_places: any # Yogeshwar
  google_fonts: ^1.1.1
  intl: any # Yogeshwar Date / Time format parsing
  geolocator: ^5.3.1 # Yogeshwar Finding Location of user to fetch Latitude and Longitude
  geocoding: #Aswin for Getting lat and long from Address
  flutter_svg: any # Yogeshwar SVG Picture inclusion library from assets
  image_picker: ^0.6.7+17 # Yogeshwar
  flutter_spinkit: ^4.1.2+1 # Yogeshwar Spin kits for loading indicators during API calls
  flutter_icons: any
  keyboard_service: ^1.0.3 # Yogeshwar Service to dismiss keyboard
  share: ^0.6.5+4 # Yogeshwar sharing app
  io: ^0.3.4 # Yogeshwar File Input / Output addition
  multi_image_picker: any #Aswin To select the Multiple Images from gallery
  flutter_absolute_path: ^1.0.6 #Aswin To Get the path of the Assets
  flutter_bloc: ^2.0.0 # Yogeshwar BLOC Pattern for parsing API / Network calls
  equatable: ^1.0.3
  carousel_slider: ^2.3.1 # Yogeshwar Images corousel for sliding various images
  bubble_tab_indicator: ^0.1.4 #Aswin Terms and Conditions Bubble Tab Bar View
  chips_choice: ^2.0.1 # Yogeshwar make chips dynamically from list
  favorite_button: ^0.0.3 # Yogeshwar Favorite button for making Therapist
  path_provider: any
  infinite_listview: ^1.0.0
  horizontal_center_date_picker: any


  sign_in_with_apple: any 


  date_util: ^0.1.4

  url_launcher: any #Aswin for Mail app launch
  flutter_statusbarcolor: ^0.2.3 #Aswin StatusBar Color

  shimmer_animation: any #Yogeshwar - Shows loading Shimmer effect while parsing API data..
  flutter_chat_bubble: ^1.0.2 # Yogeshwar chat bubbles for one to one chat user screen

  firebase_messaging: 7.0.3  # Yogeshwar Firebase push notification configuration


  simple_tooltip: ^0.1.16 # Yogeshwar tooltip customize popup
  dotted_border: ^1.0.7 # Yogeshwar for Circle rounded border
  table_calendar: ^2.3.3 #Gowtham for calendar Build
  awesome_dialog: any
  flutter_overlay_loader: ^0.0.2
  lazy_load_scrollview: 1.1.0
  cached_network_image: any
#  stripe_payment:
  super_tooltip: any
  time: any

  location: any

  googleapis: #Aswin Google Calendar Api
  googleapis_auth: # Aswin Google Cloud Authentication

  scrollable_positioned_list: ^0.1.10 #Aswin for List Manual Scrolling
  cloud_firestore: any
  firebase_core: any
  firebase_analytics: any
  firebase_auth: any
  firebase_storage: any

  json_annotation: any
  flutter_datetime_picker: any

  #keyboard_visibility: 4.0.3


  video_player: ^0.10.12
  keyboard_actions: ^3.3.1+1


  animated_text_kit: any



  readmore: any #Gowtham Text ReadMore
  argon_buttons_flutter: any
  flutter_stripe_payment: any
  flutter_document_picker: any
  flutter_file_dialog: any
  flutter_webview_plugin: any
  translator: any







dev_dependencies:
  build_runner: any
  json_serializable: any
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images_gps/
    - assets/privacy_policy/
    - assets/provider_tutorial/
    - assets/user_tutorial/
    - assets/images_gps/subCategory/esthetic/
    - assets/images_gps/subCategory/fitness/
    - assets/images_gps/subCategory/osteopathic/
    - assets/images_gps/subCategory/relaxation/









    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:


  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/notofonts/NotoSansJP-Black.otf
        - asset: assets/fonts/notofonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/notofonts/NotoSansJP-Light.otf
        - asset: assets/fonts/notofonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/notofonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/notofonts/NotoSansJP-Thin.otf
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
