name: gps_massageapp
description: A GPS Massage Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_line_sdk: ^1.3.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  curved_navigation_bar:
  flutter_markdown: ^0.5.1
  pin_code_fields: ^5.2.0
  flutter_rating_bar: ^3.2.0+1
  connectivity:
  shared_preferences:
  provider: any
  dio: any
  toast:
  sqflite: any
  getwidget: any
  http: ^0.12.2
  uuid: ^2.0.4
  flutter_google_places: any
  #  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  intl: any
  geolocator: ^5.3.1
  animated_text_kit: ^1.1.0
  flutter_svg: any
  multiselect_formfield: ^0.1.5
  image_picker: ^0.6.7+17
  flutter_spinkit: ^4.1.2+1
  flutter_icons: any
  logger: ^0.8.3
  pretty_dio_logger: ^1.1.0
  protobuf: ^1.0.1
  progress_dialog: ^1.2.4
  keyboard_service: ^1.0.3
  share: ^0.6.5+4
  io: ^0.3.4
  multi_image_picker: any #Aswin To select the Multiple Images from gallery
  flutter_absolute_path: ^1.0.6 #Aswin To Get the path of the Assets
  flutter_bloc: any
  equatable: ^1.0.3
  carousel_slider: ^2.3.1
  bubble_tab_indicator: ^0.1.4 #Aswin Terms and Conditions Bubble Tab Bar View
  chips_choice: ^2.0.1
  shimmer: ^1.1.2
  favorite_button: ^0.0.3
  path_provider: any
  infinite_listview: ^1.0.0
  horizontal_center_date_picker: ^1.0.0+2
  apple_sign_in: ^0.1.0
  date_util: ^0.1.4
  #lazy_data_table: ^0.2.1 #Aswin for Provider Schedule Calendar
  url_launcher: ^5.7.10 #Aswin for Mail app launch
  flutter_statusbarcolor: ^0.2.3 #Aswin StatusBar Color
  #flutter_week_view: ^1.0.0+2
 


  syncfusion_flutter_calendar: ^18.4.35
  flutter_chat_bubble: ^1.0.2
  firebase_messaging: ^6.0.16
  adhara_socket_io: ^0.4.2+1


#  flutter_line_login: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images_gps/
    - assets/privacy_policy/
    - assets/provider_tutorial/
    - assets/user_tutorial/









      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:


  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
